# Usa a imagem oficial do SQL Server 2019
FROM mcr.microsoft.com/mssql/server:2019-latest

# Variáveis obrigatórias
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=SenhaForte123

# Porta padrão do SQL Server
EXPOSE 1433

